name: CI

run-name: Id ${{ github.run_id }} by ${{ github.actor }}
on:
  push:
    branches:
      - master
jobs:
  passing_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Intall requirements
        run: pip install -r requirements.txt
      - name: Tests
        run: python pytest 